### ISSUE TITLE
compiling error: TOX_AVATAR_MAX_DATA_LENGTH and TOX_AVATAR_FORMAT_PNG undefined

### ISSUE THREAD

**Issue by rdissertori** [qTox/qTox#1525]
Hi,
I'm on Manjaro and trying to install qtox via the AUR repostitory which means I'm getting a git clone.
Now it seems I'm getting

> src/widget/form/profileform.cpp:217:25: Fehler: »TOX_AVATAR_MAX_DATA_LENGTH« wurde in diesem Gültigkeitsbereich nicht definiert
>      if (bytes.size() >= TOX_AVATAR_MAX_DATA_LENGTH)
> src/widget/form/profileform.cpp:226:25: Fehler: »TOX_AVATAR_MAX_DATA_LENGTH« wurde in diesem Gültigkeitsbereich nicht definiert
>      if (bytes.size() >= TOX_AVATAR_MAX_DATA_LENGTH)
> src/widget/form/profileform.cpp:232:33: Fehler: »TOX_AVATAR_FORMAT_PNG« wurde in diesem Gültigkeitsbereich nicht definiert
>      Nexus::getCore()->setAvatar(TOX_AVATAR_FORMAT_PNG, bytes);

for 2 releases already, so a fix would be welcome. It's a german error message and means those two variables have not been defined there. Thanks

**Comment by strk** [comment]
It is due to an incompatibility between toxcore and qtox master branch.
If you use simple_make.sh for building, then pull request #1526 should fix the problem for you.
Otherwise manually install older toxcore as per instruction in https://lists.tox.im/pipermail/general/2015-April/000028.html

**Comment by rdissertori** [comment]
Oh thanks a lot @strk I wasn't aware of a fix although I was searching for it - not good enough it seems.
edit: I was just wondering why the hell your fix didn't get pulled - theres nothing worse than a dysfunctional code in a master branch from an "official" AUR repo

**Comment by strk** [comment]
@rdissertori : voice your concerns in the PR, I dunno why it doesn't want to be merged either...

**Comment by agilob** [comment]
Because it's a temporary solution that will have to be removed very soon, it doesn't fix anything permanently or for more users, the fix is only for users who compile qTox from sources.
