### ISSUE TITLE
[Regression] avatar is not being sent when there's an ongoing file transfer to contact

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1702]
Description:
In a case where there is an active file transfer between `qTox S` and `qTox R`, when `qTox S` changes its avatar, `qTox R` doesn't receive it until ongoing file transfer is finished / paused.
Basically an extension of #1693

Info:
OS: Hardened Gentoo Linux x86_64
qTox version: a841224683116e75852d6d2ebc9a9f1dc70ec957

Reproducible: Always

Steps to reproduce:
1. Start sending big file from one qTox instance to another
2. Set / change avatar

What happened:
`qTox S` doesn't send avatar to `qTox R` while there is an ongoing file transfer with `qTox R`.

What should happen:
`qTox S` should send avatar to `qTox R` while there is an ongoing file transfer with `qTox R`.

**Comment by tux3** [comment]
I'm not sure if we should even attempt to work around this one.

I suppose we could pause all user file transfers until the new avatar is sent to force core to prioritize avatars, but this should really be addressed in toxcore.

**Comment by zetok** [comment]
IMHO it just should stay open until toxcore will allow for something more than just 1 active file transfer per contact, and there should be reported bug against toxcore, linking to this issue.

**Comment by tux3** [comment]
@zetok Have you opened an issue against toxcore and spammed @irungentoo's inbox yet?

**Comment by zetok** [comment]
No, since for that I would also have to test how µTox behaves in same scenario, report bug against µTox to confirm that it's client-independent, and then fill a bug in toxcore. Waay too much work.. unless you're asking me to do that?

I mean, I would rather prefer to spend time testing ffmpeg branch, but..

**Comment by ghost** [comment]
Confirmed that it's still an issue in b4083f007446c97c400f60a5f639111d902dc160. Reproducible sending a file from uTox to qTox too. Issue created at uTox.

**Comment by agilob** [comment]
Well. actually, avatar is not even send when contact connects, at least I waited ~2weeks before I got my avatar from qtox sent to antox.

**Comment by ghost** [comment]
Updated instantly in both directions for me in uTox/qTox.

**Comment by GrayHatter** [comment]
tested uTox 0.4.2 to 0.4.2, no issue

**Comment by ghost** [comment]
@zetok Confirmed as a toxcore issue https://github.com/GrayHatter/uTox/issues/39#issuecomment-156257789

**Comment by zetok** [comment]
@kehugter not quite. It _might_ be considered to be a toxcore issue given that file transfers in toxcore have changed to default to non-parallel file transfers, but with that being said, clients should be able to "queue" and prioritize transfers on their own - i.e. in this particular case qTox could transparently to the user pause regular file transfer for a moment to send avatar, and resume regular file transfer after avatar gets instantly transmitted.

@GrayHatter ↑

**Comment by ghost** [comment]
I could be missing something, but no parallel transfers seems like a step backwards. It makes more sense to have the feature available and let the clients figure out how to prioritise each transfer and nothing else. Particularly, not creating algorithms for pseudo-parallel transfers.

**Comment by sudden6** [comment]
c-toxcore now does parallel file transfers so this should be fixed. If not, please make a new issue and reference this one.
