### ISSUE TITLE
Virtual cam: preview not working in the settings tab

### ISSUE THREAD

**Issue by An-dy** [qTox/qTox#1929]
I made a simulated web-cam. It uses a static pic to produce a 1 fps video stream.
  modprobe -vv v4l2loopback max_width=800 max_height=600
  nice -n 19 ffmpeg -loop 1 -re -i picture_800x600.png -r 1 -f v4l2 /dev/video0
![screenshot-1](https://cloud.githubusercontent.com/assets/12451368/8399699/696d95d6-1e67-11e5-88ec-14c7be6a4d55.png)
The simulated web-cam works with qtox. A video call to EchoBot is displaying the stream (after a while).
The fps is really 1. Verified with a (also working) flash broadcast application.

**Comment by tux3** [comment]
The FPS part is due to how the video drivers work, we ask the drivers to give us a range from the minimum to the maximum FPS available at a given resolution, and we take the max the video source can deliver.

Here even though your source streams at 1 FPS, qTox is told it can read at up to 30 FPS, so we trust the driver.

I pushed a fix for the preview, can you confirm that it works now?

**Comment by An-dy** [comment]
The preview still not work.
I agree, updating the driver fps information is actually my task.
  sudo modprobe v4l2loopback max_width=800 max_height=600
  echo '@1' | sudo tee /sys/devices/virtual/video4linux/video0/format
  nice -n 19 ffmpeg -loop 1 -re -i picture_800x600.png -r 1 -f v4l2 /dev/video0
![screenshot-2](https://cloud.githubusercontent.com/assets/12451368/8406919/b58b29c6-1eb5-11e5-94c3-870b575c3552.png)

**Comment by An-dy** [comment]
I changed the FPS to 25 with:
echo '@25' | sudo tee /sys/devices/virtual/video4linux/video0/format
nice -n 19 ffmpeg -loop 1 -re -i $1 -r 25 -f v4l2 /dev/video0
This does not change anything. The problem is not the low fps rate.
The problem seems to be the raw video format.
Changing the video output format to yuv420p with:
nice -n 19 ffmpeg -loop 1 -re -i $1 -r 25 -pix_fmt yuv420p -f v4l2 /dev/video0
produce a new message in the log.
[video4linux2,v4l2 @ 0xa403e20] The v4l2 frame is 720000 bytes, but 1440000 bytes are expected
instead of:
[07:25:55.367] src/video/videoframe.cpp:110 : Warning: None of the frames are valid! Did someone release us?
Anything else I can do to encircle the bug ?
(I always update my qtox git clone and compile if necessary some minutes before I test things)

**Comment by An-dy** [comment]
I spend more time in encircle the bug.
In src/video/videoframe.cpp:
else if (pixFmt == AV_PIX_FMT_RGB24) does not recognize the rgb24 input of  ffmpeg -loop 1 -re -i pic.png -r 25 -pix_fmt rgb24 -f v4l2 /dev/video0
Where does  int pixFmt  come from ?

**Comment by sudden6** [comment]
Closing because many things changed in video and this bug report is quite old. Please comment if still not fixed.
