### ISSUE TITLE
qTox should use all camera resolutions

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#5065]
My v4l2 camera allows up to 1920x1080 for H.264 format, and up to 2304x1536 for YUYV 4:2:2 format.

The largest video size qTox offers is 1080. This is probably because 1080 is the largest size for H.264 codec.

qTox shouldn't ignore higher sizes because they allow better picture quality. qTox should use ffmpeg or maybe openh264 library to encode H.264 in CPU when possible.

**Comment by anthonybilinski** [comment]
It looks like this is from `AVForm::updateVideoModes` pruning `allVideoModes` using `AVForm::selectBestModes` which has:
```
    // Identify the best resolutions available for the supposed XXXXp resolutions.
    std::map<int, VideoMode> idealModes;
    idealModes[120] = VideoMode(160, 120);
    idealModes[240] = VideoMode(430, 240);
    idealModes[360] = VideoMode(640, 360);
    idealModes[480] = VideoMode(854, 480);
    idealModes[720] = VideoMode(1280, 720);
    idealModes[1080] = VideoMode(1920, 1080);
```
so we're intentionally limiting the video modes to only ones that both the camera supports and that are close to one of these options, instead of showing all resolutions the camera supports. It looks like this originates from f595f4f81715bb305827c93e9a16c838558fda53 with the commit message "camera res option reduction" so I guess the motivation is just to reduce the number of options in the drop-down. Not sure if it's best to just keep incrementally modifying our list of "best resolutions" every time cameras get better, or if this could be done programmatically  somehow, also I'm not sure exactly how needed this is.

**Comment by Diadlo** [comment]
@anthonybilinski It's because some cameras has a lot of supported resolutions resolutions. For example my:
```
$ v4l2-ctl --list-formats-ext | grep Size | sort | uniq
		Size: Discrete 1024x576
		Size: Discrete 1184x656
		Size: Discrete 1280x720
		Size: Discrete 1280x960
		Size: Discrete 160x120
		Size: Discrete 176x144
		Size: Discrete 320x176
		Size: Discrete 320x240
		Size: Discrete 352x288
		Size: Discrete 432x240
		Size: Discrete 544x288
		Size: Discrete 640x360
		Size: Discrete 640x480
		Size: Discrete 752x416
		Size: Discrete 800x448
		Size: Discrete 800x600
		Size: Discrete 864x480
		Size: Discrete 960x544
		Size: Discrete 960x720
```

**Comment by yurivict** [comment]
Higher resolutions, in particular, afford better video quality, which is certainly desirable in many situations.

**Comment by Diadlo** [comment]
@yurivict If you have bad connection, then higher resolution will produce worse quality, than medium resolution

**Comment by tox-user** [comment]
So it looks like there are many resolutions that people don't care about and we only list the most important ones. Let's just manually add more resolutions to the list.

**Comment by anthonybilinski** [comment]
That's true, users may run into network or CPU restrictions, but the same could be said about any high resolution depending on user's environment. @yurivict can you try https://github.com/qTox/qTox/pull/5075 and see if it works for you? I don't have a fancy high resolution camera to test with :)

**Comment by anthonybilinski** [comment]
On second thought, my change won't work for @yurivict because his resolution of 2304x1536 is too far from the standard 1440p resolution that I added. I'll work on something smarter.

**Comment by yurivict** [comment]
It should read the list of resolutions from the camera.

Maybe some lower resolutions should be skipped, but several highest resolutions should certainly be kept.

The highest resolutions my camera supports can only work with USB3 with in-CPU MPEG encoding. My camera isn't even too expensive now, it costs only around $60. I'm sure there are much higher-end cameras available.

**Comment by anthonybilinski** [comment]
It does read the list of resolution from the camera, it just doesn't show the entire list because some cameras show many many resolutions that are all similar, like Diadlo showed. We reduce the number shown to make it easier for the user.

I've changed the calculation to check if a mode should be shown to use threshold that scales with the resolution to always be within 10%, instead of a hardcoded 300 pixels, which should now work for @yurivict. This will also show fewer low resolution options.

10% is equal to the initial hardcoded 300 pixels for 1920 x 1080 resolution.

**Comment by eatdust** [comment]
It is not clear to me if the commit is active in 1.15.0, because all my uvc cameras only show a resolution of 120pixels (which sucks). And, some of them are actually not working properly at that resolution, the images are full of horizontal green lines. So I suspect something is still wrong with the video res settings!
Let me know if I need to open a new bug (qtox-1.15.0, toxcore 0.2.2)
cheers.

**Comment by tox-user** [comment]
Yes, this change was included in 1.15.0.

**Comment by tox-user** [comment]
@eatdust your problem might be unrelated. You should open a new issue.
