### ISSUE TITLE
Groupchats do not honour friend aliases

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#781]
From IRC:

PrW | If I am in groupchat I can not change the names of the people who are in group chat. Although one person is "Person A" in my friend list - in group chat he has another name

**Comment by suhr** [comment]
Should we actually have the same name in groupchat and anywhere else?

**Comment by zetok** [comment]
Honouring aliases only introduces bugs
![screenshot](https://cloud.githubusercontent.com/assets/3148759/5384055/7d2053f4-80ae-11e4-8c6b-18f84c98c042.png)
![ s screenshot](https://cloud.githubusercontent.com/assets/3148759/5384058/81f51c98-80ae-11e4-9086-92c6ccd9ca3f.png)
↑ contact removed me from friend list, changed its nick, and even though was shown as offline, qTox still displayed old nick in groupchat, after re-adding still old nick was shown in groupchat. Only nick change did help with situation.

Please fix

**Comment by dubslow** [comment]
fjreegman wasn't an alias on your part, it was simply the last known name of the contact from your qTox's perspective?

@apprb

**Comment by zetok** [comment]
From what I see qTox seems to use nick as an alias (i.e. it is shown as default alias when setting alias). Thus I thought that it's a problem with aliases..

Yes, that's the last name that was shown; I didn't explicitly set an alias to it.

**Comment by apprb** [comment]
As part of resolving names in a group chat procedure qTox tries to find friend with the same ToxID as a group peer, on success it uses displayed friend name.
If somebody after deleting you from his friendlist changes nick your client still uses old nick because in your client hasn't received this changing.
Also group peers names list updates only if somebody leave/enter a group or if somebody changes own nick.

update 1: thing that really should be fixed is regenerating group peer names after friend alias changing for group where this friend is in.

**Comment by anoadragon453** [comment]
Not reproducible with the latest build.

**Comment by zetok** [comment]
Actually, I can still reproduce on newest qTox, one just has an alias set for friend; reopening.

**Comment by anoadragon453** [comment]
To be clear one cannot show an alias to one contact and a separately-named alias to different users, one possible solution is to show both. See #1195

**Comment by sudden6** [comment]
Alias and name in group now always matches.
